name: Test Workflow

on:
  push: # Trigger the workflow on code push
    branches:
      - main # Only trigger for changes to the main branch

jobs:
  test-job:
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run a Test Command
        run: echo "Hello, GitHub Actions! This is a test workflow."
