name: Validate HTML Assignment

on:
  workflow_dispatch:
    inputs:
      student_code:
        description: "HTML code submitted by the student"
        required: true

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy

      - name: Save Submitted Code
        run: echo "${{ github.event.inputs.student_code }}" > student_code.html

      - name: Validate HTML
        run: |
          tidy -q -e student_code.html || echo "Validation failed!"

      - name: Log Validation Result
        run: echo "HTML validation complete. Check the logs for errors."
